### ISSUE TITLE
Multiline strings

### ISSUE THREAD

**Issue by derula** [RyogaMasaki/jstrings#2]
Hi, first, fantastic tool, really helpful!

Currently, if a string contains a line break (0x0a / 0x0d0a), it will be detected as two separate strings instead. I understand that due to the tool's line-by-line output, representing newlines in a single string is not well-defined. However, in my use case, splitting the strings is causing some trouble.

Here's the scenario:

1. I have 2 binaries, one Japanese, one English.
2. I want to reverse engineer which strings from the Japanese binary have been translated to which in the English binary.
3. Finally, I want to apply the same changes to a newer version of the Japanese binary.

For example, the Japanese binary contains this string:

```
データベースファイル
%sが
ありませんでした
```

In the English binary, it was translated as follows:

```
Cannot find database file:
%s
```

However, `jstrings` finds each line as a separate string. In order to meaningfully do what I'm trying to do, I would need to somehow stitch these individual lines back together. Of course, I could do that manually, but with a total of over 160,000 strings found, that could be quite cumbersome, and need repeating every time a new Japanese binary is released.

Would it be possible to add a command line option that enables finding multiline strings? Perhaps some sort of escape sequence could be used to mark the CR/LF characters.

Thanks for your great work and consideration of my case.

**Comment by drojaazu** [comment]
Hi, thanks for the feedback! Off the top of my head, I believe this happens because CR/LFs are outside of viewable JIS/ASCII characters (i.e. control codes). It is considered to be the "end of a string" as soon as any non-viewable/valid byte is hit. So to get around that, we would need a list of bytes that should be considered valid for/part of the string output.

Your use case seems the most valid, so I think for now I'll add an option to include CR and/or LF as bytes to include in the output, as a single string, probably as \0A or \0D\0A or something like that.

**Comment by drojaazu** [comment]
I have added a multiline option and published v1.5: https://github.com/drojaazu/jstrings/releases/tag/1.5
Let me know if this is what you're looking for and I will close this out. The other issues you brought up may take a while to address, but hopefully this will be helpful for now.

**Comment by derula** [comment]
Yep, that seems very useful indeed! Thanks.
